### ISSUE TITLE
Compiling Error for baremetal zcore using rustc 1.56.0-nightly (08095fc1f 2021-07-26)

### ISSUE THREAD

**Issue by chyyuu** [chyyuu/zCore#1]
```
cd zCore && make run mode=release linux=1
```
Got errors:
...
error: could not compile `rlibc-opt` due to 60 previous errors; 1 warning emitte
....

rustc 1.56.0-nightly can not compile rlibc-opt  crate correctly.

How to fix?

@wangrunji0408

**Comment by GCYYfun** [comment]
I guess it's because it uses the AT&T syntax for assembly.
The rustc default assembly format seems to be Intel syntax.

Reference:https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#bad-asm-style
```
On x86, asm! uses the intel assembly syntax by default. 
While this can be switched using assembler directives like .att_syntax, 
using the att_syntax option is recommended instead 
because it will also properly prefix register placeholders with % as required by AT&T syntax.
```
I guess a less elegant way might be to add ```.att_syntax``` to the first line of the assembly file 
and then remove ```#![deny(warnings)]``` from lib.rs.

**Comment by chyyuu** [comment]
Yes! Fixed. Change x86_64.S from AT&T syntax to intel syntax.
